package com.dineup.service.error;

public enum ErrorKey {
    INCOMPLETE_COORDINATE,
    INCOMPLETE_AREA,
    UNSPECIFIED_IDENTIFIER,
    UNSPECIFIED_USER_TOKEN,
    INVALID_COMMENT_REQUEST,
    PROFILE_LOAD_FAILED,
    OBJECT_NOT_FOUND,
    GENERAL_ERROR
}
